#!/bin/bash

#####
# Parallelization architecture / middleware
#####

# PINCRAM_ARCH=bash
# PINCRAM_ARCH=ge
PINCRAM_ARCH=pbs
export PINCRAM_ARCH
# export PINCRAM_QUEUE=myqueue ## Gets added to qsub call with -q option
# export PINCRAM_CHUNKSIZE=1 ## Number of registrations per array subjob

# export PINCRAM_USE_MIRTK=1 ## Port to MIRTK not usable yet

export $PINCRAM_PBS_OPTION="-l place=free" ## Per-system options

#####
# Execution parameter
#####

export PINCRAM_PROCEED_PCT=100 ## Minimum % ratio of expected atlas transformations on which to continue
                               ## Trades off reproducibility and accuracy against speed
                               ## Reduce for rapid testing or when jobs are executed unreliably

#####
# For new installation: adapt paths to dependencies
#####

PATH=/***PATH/TO***/niftyreg/bin:$PATH

PATH=/***PATH/TO***/niftyseg/bin:$PATH

slicer_modules=Slicer-4.6.2-linux-amd64/lib/Slicer-4.6/cli-modules
PATH=/**PATH/TO***/slicer/$slicer_modules:$PATH

LD_LIBRARY_PATH=/***PATH/TO/slicer/$slicer_modules:/***PATH/TO***/slicer/$slicer_modules/..:$LD_LIBRARY_PATH

