#!/bin/bash

msg () {
    for msgline
    do echo "$pn: $msgline" >&2
    done
}

log () {
    for msgline
    do echo "$pn: $msgline" >>noisy.log
    done
}

fatal () { msg "$@"; exit 1; }

tempdir () {
    : ${TMPDIR:="/tmp"}
    tdbase=$TMPDIR/$USER
    test -e $tdbase || mkdir -p $tdbase
    td=$(mktemp -d $tdbase/$(basename $0).XXXXXX) || fatal "Could not create temp dir in $tdbase"
    echo $td
}

normalpath () {
    local s=$1
    [[ $s == ${s::400} ]] || fatal "Option path too long"
    [[ $s == ${s//[^[:print:]]/} ]] || fatal "Non-printables in path"
    dir=$(dirname "$1")
    bas=$(basename "$1")
    echo $(cd $dir && pwd)/$bas
}

export ARCH=pbs

export PATH=~/software/niftyseg/build/seg-apps:$PATH
export PATH=~/software/irtk-git/bin:$PATH

set -e   # Terminate script at first error
