#!/bin/bash

#####
# Parallelization architecture / middleware
#####

# PINCRAM_ARCH=bash
# PINCRAM_ARCH=ge
PINCRAM_ARCH=pbs
export PINCRAM_ARCH
# export PINCRAM_QUEUE=myqueue ## Gets added to qsub call with -q option
# export PINCRAM_CHUNKSIZE=1 ## Number of registrations per array subjob
export $PINCRAM_PBS_OPTION="-l place=free" ## Per-system options


#####
# To use MIRTK in place of IRTK (experimental, results slightly inferior)
#####

# export PINCRAM_USE_MIRTK=1 
#PATH=/***PATH/TO***/mirtk/build-gcc/lib/tools:$PATH
#LD_LIBRARY_PATH=/***PATH/TO***/mirtk/build-gcc/lib:$LD_LIBRARY_PATH


#####
# Execution parameter
#####

export PINCRAM_PROCEED_PCT=100 ## Minimum % ratio of expected atlas transformations on which to continue
                               ## Trades off reproducibility and accuracy against speed
                               ## Reduce for rapid testing or when jobs are executed unreliably

#####
# For new installations: adapt paths to dependencies
#####

PATH=/***PATH/TO***/niftyseg/bin:$PATH  ## https://sourceforge.net/projects/niftyseg/

PATH=/***PATH/TO***/irtk/bin:$PATH ## https://github.com/BioMedIA/IRTK -- currently needed even if MIRTK set

export PATH
