#!/bin/bash

p=$1 ; shift
r=$1 ; shift

cdir=$(dirname $0)
. $cdir/common
cdir=$(normalpath $cdir)

c=$(normalpath $i)

pincram.sh $c -tpn $cdir/neutral.dof.gz -result $r -atlas $cdir/../atlas -par 1 -levels 3
