#!/bin/bash

p=$*

test -e results || mkdir results
test -e temp || mkdir temp

cdir=$(dirname $0)
. $cdir/common
cdir=$(normalpath $cdir)

for i in $p ; do

    c=$(normalpath $i)
    pincram.sh $c -tpn $cdir/neutral.dof.gz -result $PWD/results/$(basename $c) -output $PWD/temp -atlas $cdir/atlas -par 60 -levels 3

done
