#!/usr/bin/env bash

#####
# Parallelization architecture / middleware
#####

PINCRAM_ARCH=bash
# PINCRAM_ARCH=bash-single
# PINCRAM_ARCH=ge
# PINCRAM_ARCH=pbs
export PINCRAM_ARCH
# export PINCRAM_QUEUE=myqueue ## Gets added to qsub call with -q option
# export PINCRAM_CHUNKSIZE=1 ## Number of registrations per array subjob
# export PINCRAM_PBS_OPTION="-l place=free" ## Per-system options


#####
# Registration library to use
#####

# Options are mirtk (recommended), greedy (under development), or irtk (deprecated)

export PINCRAM_USE_LIB=irtk 


#####
# Execution parameter
#####

export PINCRAM_PROCEED_PCT=100 ## Minimum % ratio of expected atlas transformations on which to continue
                               ## Trades off reproducibility and accuracy against speed
                               ## Reduce for rapid testing or when jobs are executed unreliably


#####
# Set search path
#####

base_sw_path=$HOME/software 

## Required -- pincram
PATH=$base_sw_path/pincram:$PATH

## Required -- https://sourceforge.net/projects/niftyseg/
PATH=$base_sw_path/niftyseg/build/seg-apps:$PATH

## Required -- https://github.com/BioMedIA/MIRTK 
PATH=$base_sw_path/mirtk/install/bin:$PATH

## Optional -- https://github.com/BioMedIA/IRTK 
# PATH=$base_sw_path/irtk/bin:$PATH 

## Optional https://sourceforge.net/projects/niftyseg/
# PATH=$base_sw_path/greedy/build:$PATH  

export PATH LD_LIBRARY_PATH

#####
# Call pincram
#####

pincram.sh $1 -result result -atlas atlas
x